import "infra/__generated__/LoginPageLogoutMutation.graphql.ts"
import "infra/__generated__/GoogleDriveFilePickerQuery.graphql.ts"
import "infra/__generated__/GoogleDriveFilePickerLinkGoogleAccountMutation.graphql.ts"
import "infra/__generated__/InternalBfPageCreateIngestionJobMutation.graphql.ts"
import "infra/__generated__/LoginPageLoginWithGoogleMutation.graphql.ts"
import "infra/__generated__/LoginPageCVQuery.graphql.ts"