/* @generated */
import "infra/__generated__/LoginPageLogoutMutation.graphql.ts"
import "infra/__generated__/LoginPageLoginWithGoogleMutation.graphql.ts"
import "infra/__generated__/LoginPageCVQuery.graphql.ts"
import "infra/__generated__/PlaygroundPageMutation.graphql.ts"
import "infra/__generated__/RandallPlaygroundPageMutation.graphql.ts"
import "infra/__generated__/IBfOrganizationsPageQuery.graphql.ts"
import "infra/__generated__/IBfOrganizationsPage_BfOrganization.graphql.ts"
import "infra/__generated__/RandallPlaygroundPageAddToGoogleMutation.graphql.ts"
import "infra/__generated__/RandallPlaygroundPageQuery.graphql.ts"
import "infra/__generated__/RandallPlaygroundPagePickFolderMutation.graphql.ts"