CREATE TABLE IF NOT EXISTS bfDb (
  bf_gid VARCHAR(255) PRIMARY KEY,
  bf_oid VARCHAR(255) NOT NULL,
  bf_cid VARCHAR(255) NOT NULL,
  bf_sid VARCHAR(255),
  bf_tid VARCHAR(255),
  class_name VARCHAR(255),
  last_updated TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE,
  props JSONB NOT NULL
);
