CREATE TABLE IF NOT EXISTS bfDb (
  bf_Gid VARCHAR(255) PRIMARY KEY,
  PK VARCHAR(255) NOT NULL,
  SK VARCHAR(255),
  props JSONB NOT NULL,
  bf_Pid VARCHAR(255),
  bf_Oid VARCHAR(255),
  sort_Value VARCHAR(255),
  class_Name VARCHAR(255),
  created_At TIMESTAMP WITHOUT TIME ZONE,
  last_Updated TIMESTAMP WITHOUT TIME ZONE
);
