CREATE TABLE IF NOT EXISTS bfDb (
  bf_Gid VARCHAR(255) PRIMARY KEY,
  bf_Pid VARCHAR(255),
  bf_Oid VARCHAR(255) NOT NULL,
  bf_Tid VARCHAR(255),
  class_Name VARCHAR(255),
  props JSONB NOT NULL,
  sort_Value VARCHAR(255),
  last_Updated TIMESTAMP WITHOUT TIME ZONE,
  created_At TIMESTAMP WITHOUT TIME ZONE,
  PK VARCHAR(255) NOT NULL,
  SK VARCHAR(255)
);
