/* @generated */
import "packages/__generated__/ContactUsSubmitFormMutation.graphql.ts"
import "packages/__generated__/LoginPageCVQuery.graphql.ts"
import "packages/__generated__/LoginFormLoginWithGoogleMutation.graphql.ts"
import "packages/__generated__/LoginPageLogoutMutation.graphql.ts"
import "packages/__generated__/SettingsPageQuery.graphql.ts"
import "packages/__generated__/SearchMutation.graphql.ts"
import "packages/__generated__/SearchQuery.graphql.ts"
import "packages/__generated__/GoogleFilePickerQuery.graphql.ts"
import "packages/__generated__/GoogleFilePickerAddToGoogleMutation.graphql.ts"
import "packages/__generated__/GoogleFilePickerPickFolderMutation.graphql.ts"
import "packages/__generated__/SettingsMediaQuery.graphql.ts"