import "packages/__generated__/LoginPageCVQuery.graphql.ts"
import "packages/__generated__/LoginFormLoginWithGoogleMutation.graphql.ts"
import "packages/__generated__/LoginPageLogoutMutation.graphql.ts"
import "packages/__generated__/ProjectNewCreateNewProjectMutation.graphql.ts"
import "packages/__generated__/ProjectPageContainerProjectQuery.graphql.ts"
import "packages/__generated__/ProjectView_containerProject.graphql.ts"