export const DEFAULT_ADDITIONAL_JSON = {
  strokeColor: null,
  strokeWidth_px: null,
  useEndCap: false,
  capCta: "Follow for more",
  capName: "@handle",
  useTitle: false,
  titleColor: "rgba(255, 215, 0, 1)",
  titleStrokeColor: "rgba(0, 0, 0, 1)",
  titleStrokeWidth: 6,
  watermarkScale: 0.25,
};

export const DEFAULT_RENDER_SETTINGS = {
  captionColor: "rgb(255, 255, 255)", // white
  captionHighlightColor: "rgb(255, 215, 0)", // BF yellow
  captionLines: 3,
  captionWordsPerLine: 5,
  censorShowFirstLetter: true,
  censorSwears: true,
  censorUseAsterisks: true,
  font: "Roboto",
  ratio: 9 / 16,
  showCaptions: true,
  showTrackingDebug: false,
  showWatermark: true,
  template: "default",
  useAutocropping: false,
  useTracking: false,
  watermarkLogo: "made_with_bf.png",
  watermarkOpacity: 0.5,
  watermarkPosition: "under_caption",
  largeMovementThresholdPct: 0.1,
  additionalJson: JSON.stringify(DEFAULT_ADDITIONAL_JSON),
};

export const DEFAULT_TRANSCRIPT_SETTINGS = {
  start_time: 0,
  end_time: 22,
  transcript: [
    {
      word: "Um.",
      start: 1.88,
      end: 2.4,
      punctuated_word: "Um.",
      speaker: "A",
    },
    {
      word: "Hi.",
      start: 2.47,
      end: 2.958,
      punctuated_word: "Hi.",
      speaker: "A",
    },
    {
      word: "You're",
      start: 3.054,
      end: 3.238,
      punctuated_word: "You're",
      speaker: "A",
    },
    {
      word: "not",
      start: 3.254,
      end: 3.358,
      punctuated_word: "not",
      speaker: "A",
    },
    {
      word: "gonna",
      start: 3.374,
      end: 3.502,
      punctuated_word: "gonna",
      speaker: "A",
    },
    {
      word: "believe",
      start: 3.526,
      end: 3.71,
      punctuated_word: "believe",
      speaker: "A",
    },
    {
      word: "this.",
      start: 3.75,
      end: 4.286,
      punctuated_word: "this.",
      speaker: "A",
    },
    {
      word: "I'm",
      start: 4.438,
      end: 4.702,
      punctuated_word: "I'm",
      speaker: "A",
    },
    {
      word: "from",
      start: 4.726,
      end: 4.886,
      punctuated_word: "from",
      speaker: "A",
    },
    {
      word: "Idaho.",
      start: 4.918,
      end: 5.77,
      punctuated_word: "Idaho.",
      speaker: "A",
    },
    {
      word: "Maybe",
      start: 7.03,
      end: 7.406,
      punctuated_word: "Maybe",
      speaker: "A",
    },
    {
      word: "you",
      start: 7.438,
      end: 7.558,
      punctuated_word: "you",
      speaker: "A",
    },
    {
      word: "do",
      start: 7.574,
      end: 7.702,
      punctuated_word: "do",
      speaker: "A",
    },
    {
      word: "believe",
      start: 7.726,
      end: 7.958,
      punctuated_word: "believe",
      speaker: "A",
    },
    {
      word: "that.",
      start: 8.014,
      end: 8.61,
      punctuated_word: "that.",
      speaker: "A",
    },
    {
      word: "It's.",
      start: 9.51,
      end: 9.934,
      punctuated_word: "It's.",
      speaker: "A",
    },
    {
      word: "It's",
      start: 9.982,
      end: 10.27,
      punctuated_word: "It's",
      speaker: "A",
    },
    {
      word: "strange.",
      start: 10.31,
      end: 10.662,
      punctuated_word: "strange.",
      speaker: "A",
    },
    {
      word: "That",
      start: 10.726,
      end: 10.878,
      punctuated_word: "That",
      speaker: "A",
    },
    {
      word: "can.",
      start: 10.894,
      end: 11.094,
      punctuated_word: "can.",
      speaker: "A",
    },
    {
      word: "That's",
      start: 11.142,
      end: 11.366,
      punctuated_word: "That's",
      speaker: "A",
    },
    {
      word: "enough",
      start: 11.398,
      end: 11.566,
      punctuated_word: "enough",
      speaker: "A",
    },
    {
      word: "to",
      start: 11.598,
      end: 11.718,
      punctuated_word: "to",
      speaker: "A",
    },
    {
      word: "get",
      start: 11.734,
      end: 11.838,
      punctuated_word: "get",
      speaker: "A",
    },
    {
      word: "a",
      start: 11.854,
      end: 11.934,
      punctuated_word: "a",
      speaker: "A",
    },
    {
      word: "laugh",
      start: 11.942,
      end: 12.166,
      punctuated_word: "laugh",
      speaker: "A",
    },
    {
      word: "in",
      start: 12.198,
      end: 12.318,
      punctuated_word: "in",
      speaker: "A",
    },
    {
      word: "New",
      start: 12.334,
      end: 12.462,
      punctuated_word: "New",
      speaker: "A",
    },
    {
      word: "York",
      start: 12.486,
      end: 12.646,
      punctuated_word: "York",
      speaker: "A",
    },
    {
      word: "City.",
      start: 12.678,
      end: 13.062,
      punctuated_word: "City.",
      speaker: "A",
    },
    {
      word: "Really.",
      start: 13.166,
      end: 13.81,
      punctuated_word: "Really.",
      speaker: "A",
    },
    {
      word: "It",
      start: 14.39,
      end: 14.726,
      punctuated_word: "It",
      speaker: "A",
    },
    {
      word: "doesn't",
      start: 14.758,
      end: 15.006,
      punctuated_word: "doesn't",
      speaker: "A",
    },
    {
      word: "really",
      start: 15.038,
      end: 15.326,
      punctuated_word: "really",
      speaker: "A",
    },
    {
      word: "register",
      start: 15.398,
      end: 16.07,
      punctuated_word: "register",
      speaker: "A",
    },
    {
      word: "here.",
      start: 16.23,
      end: 16.55,
      punctuated_word: "here.",
      speaker: "A",
    },
    {
      word: "You",
      start: 16.59,
      end: 16.718,
      punctuated_word: "You",
      speaker: "A",
    },
    {
      word: "know,",
      start: 16.734,
      end: 16.838,
      punctuated_word: "know,",
      speaker: "A",
    },
    {
      word: "it's",
      start: 16.854,
      end: 16.958,
      punctuated_word: "it's",
      speaker: "A",
    },
    {
      word: "just",
      start: 16.974,
      end: 17.27,
      punctuated_word: "just",
      speaker: "A",
    },
    {
      word: "people",
      start: 17.35,
      end: 17.638,
      punctuated_word: "people",
      speaker: "A",
    },
    {
      word: "go,",
      start: 17.694,
      end: 18.078,
      punctuated_word: "go,",
      speaker: "A",
    },
    {
      word: "right",
      start: 18.174,
      end: 18.358,
      punctuated_word: "right",
      speaker: "A",
    },
    {
      word: "now",
      start: 18.374,
      end: 18.502,
      punctuated_word: "now",
      speaker: "A",
    },
    {
      word: "we're",
      start: 18.526,
      end: 18.638,
      punctuated_word: "we're",
      speaker: "A",
    },
    {
      word: "looking",
      start: 18.654,
      end: 18.806,
      punctuated_word: "looking",
      speaker: "A",
    },
    {
      word: "at",
      start: 18.838,
      end: 18.934,
      punctuated_word: "at",
      speaker: "A",
    },
    {
      word: "me",
      start: 18.942,
      end: 19.062,
      punctuated_word: "me",
      speaker: "A",
    },
    {
      word: "going,",
      start: 19.086,
      end: 19.27,
      punctuated_word: "going,",
      speaker: "A",
    },
    {
      word: "this",
      start: 19.31,
      end: 19.438,
      punctuated_word: "this",
      speaker: "A",
    },
    {
      word: "guy",
      start: 19.454,
      end: 19.606,
      punctuated_word: "guy",
      speaker: "A",
    },
    {
      word: "from",
      start: 19.638,
      end: 19.878,
      punctuated_word: "from",
      speaker: "A",
    },
    {
      word: "Iowa",
      start: 19.934,
      end: 20.286,
      punctuated_word: "Iowa",
      speaker: "A",
    },
    {
      word: "is",
      start: 20.318,
      end: 20.51,
      punctuated_word: "is",
      speaker: "A",
    },
    {
      word: "pretty",
      start: 20.55,
      end: 20.79,
      punctuated_word: "pretty",
      speaker: "A",
    },
    {
      word: "interesting.",
      start: 20.83,
      end: 21.15,
      punctuated_word: "interesting.",
      speaker: "A",
    },
  ],
};
